global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'biblio-frontend'
    static_configs:
      - targets: ['host.docker.internal:4200']
  
  - job_name: 'biblio-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']